[DB_client]
host = "134.155.111.193"
database = "soccerdb"
user = "project_client"
password = "papies"
port = 5433

[DB_su]
host = "134.155.111.193"
database = "soccerdb"
user = "postgres"
password = "postgres"
port = 5433

[DB_test]
host = "134.155.111.193"
database = "dbtest"
user = "testuser"
password = "testpw"
port = 5433